language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - sudo apt-get update 
    - sudo apt-get install -qq git cmake g++ libgsl0-dev 
    - pip install matplotlib numpy scipy networkx --upgrade
    - # this require latest moose.
    - git clone https://github.com/BhallaLab/moose-core --depth 50
    - cd moose-core && mkdir _build && cd _build && cmake .. && make -j`nproc` && make install

script:
    - python findSim.py ./Curated/FindSim-Jain2009_Fig4F.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig2B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Gu2004_fig3B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Ji2010_fig1C_ERK_acute.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig4C.tsv --model models/synSynth7.g
