language: cpp

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - # this require latest moose.
    - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/moose/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/home:moose.list"
    - wget -nv https://download.opensuse.org/repositories/home:moose/xUbuntu_14.04/Release.key -O Release.key
    - sudo apt-key add - < Release.key
    - sudo apt-get update 
    - sudo apt-get install -y -qq pymoose 
    - sudo apt-get install python-pip -qq
    - pip install matplotlib numpy scipy networkx --upgrade --user

script:
    - python findSim.py ./Curated/FindSim-Jain2009_Fig4F.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig2B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Gu2004_fig3B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Ji2010_fig1C_ERK_acute.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig4C.tsv --model models/synSynth7.g
