language: python
python:
   - "2.7"
   - "3.6"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - # this require latest moose.
    - sudo apt-get update 
    - sudo apt-get install graphviz python-networkx python-tk -qq

script:
    - cp ./.travis/matplotlibrc .
    - python -m pip install .
    - python -m pip install pymoose --pre --upgrade # till we relase 3.2.0
    - ./test.sh
