language: python
python:
   - "3.6"
service:
   - xvfb

before_script:
    - "export DISPLAY=:99.0"
    - sleep 3 # give xvfb some time to start
    - # this require latest moose.
    - sudo apt-get update 
    - sudo apt-get install graphviz python-networkx python-tk -qq

script:
    - cp ./.travis/matplotlibrc .
    - ./test.sh
