language: python
python:
   - "2.7"
   - "3.6"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - # this require latest moose.
    - sudo apt-get update 
    - sudo apt-get install python-scipy python-networkx python-tk python-matplotlib -qq

script:
    - cp ./.travis/matplotlibrc .
    - python -m pip install pymoose --pre --user
    - python -m pip install pylint numpy --user --upgrade 
    - find . -type f -name "*.py" | xargs -I file python -m pylint -E file
    - python findSim.py ./Curated/FindSim-Jain2009_Fig4F.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig2B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Gu2004_fig3B.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Ji2010_fig1C_ERK_acute.tsv --model models/synSynth7.g
    - python findSim.py ./Curated/FindSim-Bhalla1999_fig4C.tsv --model models/synSynth7.g
